(() => {
const form=document.querySelector('#calculator-form'), type=document.querySelector('#work-type'), box=document.querySelector('#dynamic'), error=document.querySelector('#error'), result=document.querySelector('#result'), breakdown=document.querySelector('#breakdown'), copyButton=document.querySelector('#copy-result'), copyStatus=document.querySelector('#copy-status');
let lastCopyText='';
const money=n=>`${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(n)} ₽`, fmt=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:4}).format(n);
const opts=(items)=>items.map(([v,t])=>`<option value="${v}">${t}</option>`).join('');
const field=(id,label,html,cls='')=>`<label class="field ${cls}"><span>${label}</span>${html}</label>`;
const select=(id,items)=>`<select id="${id}">${opts(items)}</select>`;
const num=(id,placeholder='0',min=0)=>`<input id="${id}" type="number" min="${min}" step="any" placeholder="${placeholder}">`;
const common=()=>field('deadline','Срок',select('deadline',[['long','7–10 рабочих дней'],['standard','3–5 рабочих дней'],['fast','До 3 рабочих дней']]))+field('font','Шрифт',select('font',[['14','14'],['12','12']]))+field('spacing','Межстрочный интервал',select('spacing',[['1.5','1.5'],['1','1.0'],['1.15','1.15']]));
const articleFormat=()=>field('font','Шрифт',select('font',[['14','14'],['12','12']]))+field('spacing','Межстрочный интервал',select('spacing',[['1.5','1.5'],['1','1.0'],['1.15','1.15']]));
const ap=()=>field('system','Система проверки',select('system',[['free','Бесплатный Антиплагиат.ру'],['paid','Платная система']]));
const pages=()=>field('pages','Количество страниц',num('pages','Например, 50',1));
const diplomaGroups={
  spo:[['spo-theory','СПО — теория без расчётов и анализа'],['spo-practice','СПО — теория + практика без проверки АП'],['spo-ap','СПО — АП до 60% (бесплатный)']],
  vo:[['vo-ap','ВО — АП 60–70% (бесплатный)']],
  chapters:[['practical-vkr','Практическая глава диплома / диссертации (АП ВУЗ)'],['chapter3','Проектная глава диплома / диссертации (АП ВУЗ)'],['theory-chapter','Теоретическая глава / пункт к диплому (50–60% на бесплатном доступе)'],['chapters','Практическая или проектная глава диплома (75%+ на бесплатном доступе)'],['chapter-calc','Расчётно-практическая / аналитическая глава'],['intro','Введение / заключение'],['refs','Список литературы'],['plan','План к диплому'],['format','Нормоконтроль и оформление'],['abstract','Автореферат (до 10 страниц)'],['review','Рецензия и сопроводительная документация'],['presentation','Презентация'],['report','Доклад']],
  revisions:[['revision','Доработки чужих ВКР']]
};
function diplomaOptionsHtml(group){if(group==='vo'){return diplomaGroups.vo.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')+[50,55,60,65,70,75,80,85].map(n=>`<option value="paid-vuz" data-originality="${n}">ВО — АП ВУЗ ${n}%+</option>`).join('')}return opts(diplomaGroups[group]||[])}
const control=id=>document.getElementById(id);
const selectedText=id=>{const e=control(id);return e?.selectedOptions?.[0]?.textContent.trim()||''};
const addParameter=(list,label,value)=>{if(value!==undefined&&value!==null&&String(value).trim()!=='')list.push(`${label}: ${String(value).trim()}`)};
function addSelected(list,id,label){const e=control(id);if(e&&!e.closest('.hidden'))addParameter(list,label||e.closest('.field')?.querySelector('span')?.textContent||id,selectedText(id));}
function addCommonParameters(list){for(const [id,label] of [['deadline','Срок'],['font','Шрифт'],['spacing','Межстрочный интервал']])addSelected(list,id,label)}
function buildCopyText(x){const workNames={course:'Курсовая',diploma:'Диплом / ВКР',test:'Контрольная',essay:'Реферат',research:'НИР / отчёт по практике',service:'Отдельная услуга'};const parameters=[],volumes=[],t=type.value;
if(t==='course'||t==='essay'){addSelected(parameters,'course-kind','Тип работы');const p=control('pages')?.value;if(p)volumes.push(`${p} страниц`);const has=control('has-ap')?.value==='yes';addParameter(parameters,'Антиплагиат',has?'С АП':'Без АП');if(has){addParameter(parameters,'Оригинальность',`${control('originality')?.value||''}%`);addSelected(parameters,'system','Система проверки')}addCommonParameters(parameters);}
else if(t==='diploma'){const k=control('diploma-kind')?.value;addSelected(parameters,'diploma-kind','Тариф');if(k==='refs'){const n=control('count')?.value;if(n!=='')volumes.push(`${n} источников`)}else if(k==='plan')volumes.push('фиксированная услуга');else if(k==='presentation'){const n=control('count')?.value;if(n)volumes.push(`${n} слайдов`)}else if(k==='report'){const n=control('count')?.value;if(n)volumes.push(`${n} листов`)}else{const p=control('pages')?.value;if(p)volumes.push(`${p} страниц`)}if(k==='paid-vuz')addParameter(parameters,'Оригинальность',`${control('originality')?.value||''}%`);addCommonParameters(parameters);}
else if(t==='test'){const parts=[['theory-pages','страниц теории'],['practice-pages','страниц практики'],['offline-test','оффлайн-тестовых вопросов'],['online-test','онлайн-тестовых вопросов'],['online-task','онлайн-задач'],['easy-off','лёгких оффлайн-задач'],['medium-off','средних оффлайн-задач'],['hard-off','сложных оффлайн-задач'],['very-hard-off','очень сложных оффлайн-задач'],['easy-task','лёгких заданий'],['medium-task','средних заданий'],['docs','документов'],['schemes','схем счетов'],['excel','заданий Excel'],['vpr','заданий ВПР'],['one-c','заданий 1С']];for(const [id,label] of parts){const n=Number(control(id)?.value||0);if(n)volumes.push(`${n} ${label}`)}addCommonParameters(parameters);}
else if(t==='research'){const mode=control('research-kind')?.value;addSelected(parameters,'research-kind','Режим НИР');if(mode==='diploma')addSelected(parameters,'chapter-kind','Тип главы');if(mode==='ap'){addParameter(parameters,'Оригинальность',`${control('originality')?.value||''}%`);addSelected(parameters,'system','Система проверки')}const p=control('pages')?.value;if(p)volumes.push(`${p} страниц`);addCommonParameters(parameters);}
else{const k=control('service-kind')?.value;addSelected(parameters,'service-kind','Услуга');if(k==='uniqueness'){addParameter(parameters,'Текущая уникальность',`${control('current')?.value||''}%`);addParameter(parameters,'Желаемая уникальность',`${control('target')?.value||''}%`);const p=control('pages')?.value;if(p)volumes.push(`${p} страниц`)}else{const p=control('pages')?.value;if(p)volumes.push(`${p} листов`);if(k?.startsWith('article'))addCommonParameters(parameters)}}
const lines=[`Тип работы: ${workNames[t]||'Работа'}`,`Объём: ${volumes.length?volumes.join('; '):'не указан'}`];if(parameters.length)lines.push(`Дополнительные параметры: ${parameters.join('; ')}`);lines.push('',`Стоимость для посредника: ${money(x.broker)}`,`Стоимость для студента: ${money(x.student)}`);return lines.join('\n')}
async function writeClipboard(text){try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return true}}catch{}const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();let copied=false;try{copied=document.execCommand('copy')}finally{area.remove()}return copied}
const courseFields=(withCommon=true)=>field('course-kind','Тип курсовой',select('course-kind',[['theory','Теория'],['practice','Практика'],['both','Теория + практика']]))+pages()+field('has-ap','Проверка на антиплагиат',select('has-ap',[['no','Без АП'],['yes','С АП']]))+`<div id="ap-fields" class="fields span-all hidden">${field('originality','Требуемая оригинальность, %',num('originality','Например, 65',0))}${ap()}</div>`+(withCommon?common():'');
function render(){const t=type.value;let s='';if(t==='course'||t==='essay')s=courseFields();
if(t==='diploma')s=field('diploma-category','Категория диплома / ВКР',select('diploma-category',[['','Выберите категорию'],['spo','Среднее профессиональное образование (СПО)'],['vo','Высшее образование (ВО)'],['chapters','Главы и части диплома / диссертации'],['revisions','Доработки чужих ВКР']]))+field('diploma-kind','Вид работы',select('diploma-kind',[['','Сначала выберите категорию']]))+`<div id="diploma-fields" class="fields span-all hidden">${pages()}${common()}<div id="extra-fields" class="fields span-all"></div></div>`;
if(t==='test')s=`<p class="hint span-all">Добавьте объёмы и количество элементов. Итог — сумма выбранных позиций.</p>${field('theory-pages','Страницы теории',num('theory-pages'))}${field('practice-pages','Страницы практики',num('practice-pages'))}${field('offline-test','Оффлайн-тест, вопросы',num('offline-test'))}${field('online-test','Онлайн-тест, вопросы',num('online-test'))}${field('online-task','Онлайн-задача, задачи',num('online-task'))}${field('easy-off','Оффлайн-задача, лёгкая',num('easy-off'))}${field('medium-off','Оффлайн-задача, средняя',num('medium-off'))}${field('hard-off','Оффлайн-задача, сложная',num('hard-off'))}${field('very-hard-off','Оффлайн-задача, очень сложная',num('very-hard-off'))}${field('easy-task','Задание, лёгкое',num('easy-task'))}${field('medium-task','Задание, среднее',num('medium-task'))}${field('docs','Документы (баланс, ОСВ и т.п.)',num('docs'))}${field('schemes','Схемы счетов',num('schemes'))}${field('excel','Excel',num('excel'))}${field('vpr','ВПР',num('vpr'))}${field('one-c','Задания 1С',num('one-c'))}${common()}`;
if(t==='research')s=field('research-kind','Режим НИР / отчёта',select('research-kind',[['noap','Без АП'],['ap','С проверкой на АП'],['diploma','Глава диплома']]))+field('chapter-kind','Тип главы',select('chapter-kind',[['theory','Теоретическая'],['analytical','Аналитическая'],['project','Проектная']]))+pages()+`<div id="research-ap" class="fields span-all hidden">${field('originality','Оригинальность, %',num('originality','Например, 65'))}${ap()}</div>`+common();
if(t==='service')s=field('service-kind','Услуга',select('service-kind',[['article65','Статья — АП 65–70% ВУЗ'],['article70','Статья — АП 70–80% ВУЗ'],['article80','Статья — АП 80%+ ВУЗ'],['uniqueness','Повышение уникальности']]))+`<div id="service-fields" class="fields span-all">${field('pages','Количество листов / страниц',num('pages','Например, 5',1))}</div>`;
box.innerHTML=s; bind();}
function bind(){const has=document.querySelector('#has-ap'), apbox=document.querySelector('#ap-fields');if(has)has.onchange=()=>apbox.classList.toggle('hidden',has.value!=='yes');const dc=document.querySelector('#diploma-category'),dk=document.querySelector('#diploma-kind');if(dc&&dk){dc.onchange=updateDiplomaCategory;dk.onchange=updateDiploma;updateDiplomaCategory()}const rk=document.querySelector('#research-kind');if(rk){rk.onchange=updateResearch;updateResearch()}const sk=document.querySelector('#service-kind');if(sk){sk.onchange=updateService;updateService()}}
function updateDiplomaCategory(){const group=document.querySelector('#diploma-category').value,kind=document.querySelector('#diploma-kind');kind.innerHTML=`<option value="">Выберите вид работы</option>${diplomaOptionsHtml(group)}`;document.querySelector('#diploma-fields').classList.add('hidden');document.querySelector('#extra-fields').innerHTML='';}
function updateDiploma(){const kind=document.querySelector('#diploma-kind').value, ex=document.querySelector('#extra-fields'), fields=document.querySelector('#diploma-fields');if(!kind){fields.classList.add('hidden');ex.innerHTML='';return}fields.classList.remove('hidden');if(kind==='refs')ex.innerHTML=field('count','Количество источников',num('count','Например, 20',0));else if(kind==='plan')ex.innerHTML='';else if(kind==='presentation')ex.innerHTML=field('count','Количество слайдов',num('count','Например, 10',1));else if(kind==='report')ex.innerHTML=field('count','Количество листов',num('count','Например, 5',1));else if(kind==='paid-vuz')ex.innerHTML='<input id="originality" type="hidden">';else ex.innerHTML='';if(kind==='paid-vuz'){const threshold=document.querySelector('#diploma-kind').selectedOptions[0]?.dataset.originality,originality=document.querySelector('#originality');if(threshold&&originality)originality.value=threshold}const fixed=['intro','refs','plan','format','abstract','review','presentation','report'].includes(kind);document.querySelector('#diploma-fields').querySelectorAll('#deadline,#font,#spacing').forEach(e=>e.closest('.field').classList.toggle('hidden',fixed));document.querySelector('#pages').closest('.field').classList.toggle('hidden',['refs','plan','presentation','report'].includes(kind));}
function updateResearch(){const mode=document.querySelector('#research-kind').value,chapter=document.querySelector('#chapter-kind');chapter.closest('.field').classList.toggle('hidden',mode!=='diploma');chapter.innerHTML=document.querySelector('#research-chapter-options').innerHTML;document.querySelector('#research-ap').classList.toggle('hidden',mode!=='ap');}
function updateService(){const k=document.querySelector('#service-kind').value, f=document.querySelector('#service-fields');if(k==='uniqueness')f.innerHTML=field('current','Текущая уникальность, %',num('current','Например, 30',0))+field('target','Желаемая уникальность, %',num('target','Например, 70',0))+field('pages','Количество страниц',num('pages','Например, 70',1));else f.innerHTML=field('pages','Количество листов',num('pages','Например, 5',1))+(k.startsWith('article')?articleFormat():'');}
type.onchange=render;render();
function val(id){const e=document.getElementById(id);return e?Number(e.value||0):0}function need(id,label,min=0){const e=document.getElementById(id);const v=e?e.value.trim():'';if(v===''||!Number.isFinite(Number(v))||Number(v)<min)throw `${label}: укажите число не меньше ${min}.`;return Number(v)}
function coeff(){return (document.querySelector('#deadline')?.value==='fast'?1.55:document.querySelector('#deadline')?.value==='standard'?1.35:1)*(document.querySelector('#font')?.value==='12'?1.5:1)*(document.querySelector('#spacing')?.value==='1'?1.5:document.querySelector('#spacing')?.value==='1.15'?1.25:1)}
function apTariff(orig,paid){let edge=orig<=40?40:orig<=50?50:orig<=60?60:orig<=70?70:orig<=80?80:90;return 1.25*1.2*edge*(paid?1.5:1)/2}
function calculate(){let base=0,apply=false,desc=[];const t=type.value;
if(t==='course'||t==='essay'){const p=need('pages','Количество страниц',1), k=document.querySelector('#course-kind').value, rate={theory:25,practice:60,both:50}[k],has=document.querySelector('#has-ap').value==='yes';base=has?p*apTariff(need('originality','Оригинальность',0),document.querySelector('#system').value==='paid'):p*rate;apply=true;desc=[`${p} страниц × ${fmt(has?apTariff(val('originality'),document.querySelector('#system').value==='paid'):rate)} ₽/страница`,has?'Расчёт с АП':'Без проверки на АП'];}
else if(t==='diploma'){const k=document.querySelector('#diploma-kind').value;if(!k)throw 'Выберите категорию и вид работы.';const p=['plan','refs','presentation','report'].includes(k)?0:need('pages','Количество страниц',1), table={'spo-theory':[70,3500,true],'spo-practice':[112.5,6500,true],'spo-ap':[125,7500,true],'vo-ap':[142,9000,true],'chapter-calc':[145,0,true],'chapters':[155,0,true],'theory-chapter':[120,0,true],'intro':[120,600,false],'format':[35,0,false],'abstract':[100,1000,false],'review':[100,300,false],'practical-vkr':[250,0,true],'chapter3':[250,0,true],'revision':[250,0,false]};if(k==='plan'){base=300;desc=['Фиксированная стоимость'];}else if(k==='refs'){base=need('count','Количество источников',0)*30;desc=['30 ₽ за источник'];}else if(k==='presentation'){base=Math.max(750,need('count','Количество слайдов',1)*75);desc=['75 ₽ за слайд, минимум 750 ₽'];}else if(k==='report'){base=Math.max(250,need('count','Количество листов',1)*50);desc=['50 ₽ за лист, минимум 250 ₽'];}else if(k==='paid-vuz'){const orig=need('originality','Оригинальность',0),rate=orig>=85?250:orig>=80?200:orig>=75?194:orig>=70?189:orig>=65?184:orig>=60?180:orig>=55?175:171;base=p*rate;apply=true;desc=[`${rate} ₽/страница`];}else{const [rate,min,coef]=table[k];base=Math.max(min,p*rate);apply=coef;desc=[`${rate} ₽/страница${min?`, минимум ${min} ₽`:''}`];}}
else if(t==='test'){const rates={'theory-pages':25,'practice-pages':60,'offline-test':20,'online-test':40,'online-task':150,'easy-off':125,'medium-off':150,'hard-off':200,'very-hard-off':300,'easy-task':25,'medium-task':55,'docs':200,'schemes':300,'excel':250,'vpr':400,'one-c':550};for(const [id,r] of Object.entries(rates))base+=val(id)*r;apply=true;desc=['Сумма выбранных элементов'];}
else if(t==='research'){const k=document.querySelector('#research-kind').value,p=need('pages','Количество страниц',1),c=document.querySelector('#chapter-kind').value,r={theory:150,analytical:190,project:200}[c];if(k==='noap')base=Math.max(1000,p*r);else if(k==='ap'){base=p*apTariff(need('originality','Оригинальность',0),document.querySelector('#system').value==='paid');}else{base=p*r;}apply=true;desc=[`${fmt(base/p)} ₽/страница`];}
else{const k=document.querySelector('#service-kind').value,p=need('pages','Количество листов / страниц',1);if(k==='uniqueness'){const cur=need('current','Текущая уникальность',0),tar=need('target','Желаемая уникальность',0);if(tar<cur)throw 'Желаемая уникальность не может быть ниже текущей.';if(tar>100||cur>100)throw 'Уникальность должна быть от 0 до 100%.';base=(tar-cur)/100*p*200;desc=[`Рост на ${tar-cur}% × ${p} страниц × 200 ₽`];}else{const r={article65:250,article70:270,article80:285,revision:250}[k];base=p*r;apply=k.startsWith('article');desc=[`${r} ₽/лист`];}}
const factor=apply?coeff():1,broker=Math.round(base*factor),student=broker*2;return {base,factor,broker,student,desc,apply};}
copyButton.addEventListener('click',async()=>{if(!lastCopyText)return;const copied=await writeClipboard(lastCopyText);copyStatus.textContent=copied?'Скопировано':'Не удалось скопировать';if(copied)setTimeout(()=>{copyStatus.textContent=''},2200)});
form.addEventListener('submit',e=>{e.preventDefault();error.textContent='';result.classList.add('hidden');try{const x=calculate(), selected=form.elements.price.value==='student'?x.student:x.broker;lastCopyText=buildCopyText(x);copyStatus.textContent='';breakdown.replaceChildren();const rows=[['Базовая стоимость',money(x.base)]];if(x.apply)rows.push(['Коэффициенты срока, шрифта и интервала',`×${fmt(x.factor)}`]);rows.push(['Стоимость для посредника',money(x.broker)],['Стоимость для студента',money(x.student)],['Расчёт',x.desc.join(' · ')]);for(const [a,b] of rows){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=a;dd.textContent=b;breakdown.append(dt,dd)}document.querySelector('#selected-label').textContent=form.elements.price.value==='student'?'Стоимость для студента':'Стоимость для посредника';document.querySelector('#selected-price').textContent=money(selected);document.querySelector('#student-price').textContent=`Посредник: ${money(x.broker)} · Студент: ${money(x.student)}`;result.classList.remove('hidden');}catch(err){error.textContent=String(err)}});
form.addEventListener('reset',()=>setTimeout(()=>{error.textContent='';result.classList.add('hidden');lastCopyText='';copyStatus.textContent='';render()},0));
})();
